export const cytoscapeStylesheet = [
  { selector: 'node', style: { 'label': 'data(label)', 'font-size': 8, 'color': '#CBD5E1', 'text-valign': 'bottom', 'text-margin-y': 4 } },
  { selector: 'node[type="Company"]',   style: { 'background-color': '#2563EB', 'width': 60, 'height': 60, 'label': 'data(label)', 'font-size': 10 }},
  { selector: 'node[type="Supplier"][available="true"]',  style: { 'background-color': '#16A34A', 'width': 35, 'height': 35 }},
  { selector: 'node[type="Supplier"][available="false"]', style: { 'background-color': '#DC2626', 'width': 35, 'height': 35 }},
  { selector: 'node[type="Supplier"][risk="HIGH"]',       style: { 'background-color': '#F59E0B', 'width': 35, 'height': 35 }},
  { selector: 'node[type="Factory"]',   style: { 'background-color': '#0891B2', 'shape': 'rectangle', 'width': 45, 'height': 30 }},
  { selector: 'node[type="Warehouse"]', style: { 'background-color': '#7C3AED', 'shape': 'diamond',   'width': 35, 'height': 35 }},
  { selector: 'node[type="Port"][disrupted="false"]', style: { 'background-color': '#0D9488', 'width': 20, 'height': 20 }},
  { selector: 'node[type="Port"][disrupted="true"]',  style: { 'background-color': '#DC2626', 'width': 20, 'height': 20 }},
  { selector: 'edge', style: { 'curve-style': 'bezier', 'target-arrow-shape': 'triangle', 'arrow-scale': 0.8 } },
  { selector: 'edge[routeStatus="active"]',    style: { 'line-color': '#16A34A', 'width': 2 }},
  { selector: 'edge[routeStatus="blocked"]',   style: { 'line-color': '#DC2626', 'width': 2, 'line-style': 'dashed' }},
  { selector: 'edge[routeStatus="rerouted"]',  style: { 'line-color': '#F59E0B', 'width': 2, 'line-style': 'dashed', 'label': '+14d', 'font-size': 8 }},
  { selector: 'edge[type="SUPPLIES"]',         style: { 'line-color': '#94A3B8', 'width': 1, 'line-style': 'dotted' }},
];

export const cytoscapeLayout = {
  name: 'fcose',
  quality: 'default',
  animate: false,
  fit: true,
  padding: 40,
  nodeSeparation: 45,
  idealEdgeLength: 55,
  edgeElasticity: 0.45,
  nodeRepulsion: 3500,
  gravity: 0.4,
  gravityRange: 1.2,
  gravityCompound: 1.0,
  gravityRangeCompound: 1.0,
  packComponents: true,
  componentSpacing: 40,
};